# Native support:
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
cache: packages
matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
      osx_image: xcode8.3
      latex: false
warnings_are_errors: true
